DEV_DATABASE_NAME: < your developent database name >
DEV_DATABASE_USERNAME: < your database username >
DEV_DATABASE_PASSWORD: < your database password >
TEST_DATABASE_NAME: < your test database name >
PROD_DATABASE_NAME: < your production database name >
PROD_DATABASE_USERNAME: < production database username >
PROD_DATABASE_PASSWORD: < production database password >
